In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
from  scipy import signal

In [2]:
epsn = 1e-12 # to avoid dividing zero.

def mean_acc(x):
    x_feat = np.mean(x)
    return x_feat

def max_acc(x):
    x_feat = np.max(x)
    return x_feat

def min_acc(x):
    x_feat = np.min(x)
    return x_feat

def median_acc(x):
    x_feat = np.median(x)
    return x_feat

def std_acc(x):
    x_feat = np.std(x)
    return x_feat

def energy_acc(x):
    x_feat = np.sum(np.power(x,2))
    return x_feat

def med_abs_dev_acc(x):
    x_feat = median_absolute_deviation(x)
    return x_feat

def perc_acc(x, percent):
    x_feat = np.percentile(x,percent)
    return x_feat

def iqr_acc(x):
    x_feat = np.percentile(x,75)-np.percentile(x,25)
    return x_feat

def ptop_acc(x):
    x_feat = np.max(x)-np.min(x)
    return x_feat

def cross_zero_acc(x):
    count = 0;
    for i in range(len(x)-1):
        if x[i] * x[i+1] < 0:
            count = count + 1 
    return count

def kurt_acc(x):
    x_feat = kurtosis(x)
    return x_feat

def kurt_index(x):
    n = len(x)
    temp1 = np.sum((x-mean_acc(x))**4)
    temp2 = (np.sqrt(var_acc(x)))**4
    return temp1/((n-1)*temp2)

def skew_acc(x):
    x_feat = skew(x)
    return x_feat

def skew_index(x):
    n     = len(x)
    temp1 = np.sum(( x - mean_acc(x) )**3)
    temp2 = (np.sqrt(var_acc(x)))**3
    return temp1/((n-1)*temp2)

def entropy_acc(x):
    x_feat = ent.permutation_entropy(x)
    return x_feat

def mean_abs_diff(x):
    x_feat = np.mean(np.absolute(x - np.mean(x)))
    return x_feat

def max_min_diff(x):
    x_feat = max(x) - min(x)
    return x_feat

def med_abs_dev(x):
    x_feat = np.median(np.absolute(x - np.median(x)))
    return x_feat

def neg_count(x):
    count = 0;
    for i in range(len(x)):
        if x[i] < 0:
            count = count + 1
    return count
    
def pos_count(x):
    count = 0;
    for i in range(len(x)):
        if x[i] > 0:
            count = count + 1
    return count

def cross_mean(x):
    count = 0;
    for i in range(len(x)-1):
        if (x[i] - np.mean(x)) * (x[i+1] - np.mean(x)) < 0:
            count = count + 1 
    return count

def above_mean(x):
    count = 0;
    for i in range(len(x)):
        if (x[i] - np.mean(x)) > 0:
            count = count + 1 
    return count

def below_mean(x):
    count = 0;
    for i in range(len(x)):
        if (x[i] - np.mean(x)) < 0:
            count = count + 1 
    return count

def number_peaks(x):
    return len(find_peaks(x))

def rms_acc(x):
    return np.sqrt(np.mean(np.square(x)))

def sr_acc(x): # square root
    return np.square(np.mean(np.sqrt(np.abs(x))))

def am_acc(x):
    return np.mean(np.abs(x))

def waveform_index(x):
    return rms_acc(x)/(am_acc(x)+epsn)

def peak_index(x):
    return max_acc(x)/(rms_acc(x)+epsn)

def impluse_factor(x):
    return max_acc(x)/(am_acc(x)+epsn)

def tolerance_index(x):
    return max_acc(x)/(sr_acc(x)+epsn)

# ###****### features for FFT domain
def fft_fft(x):
    fft_trans = np.abs(np.fft.fft(x))
    freq_spectrum = fft_trans[1:int(np.floor(len(x) * 1.0 / 2)) + 1]
    _freq_sum_ = np.sum(freq_spectrum)
    return freq_spectrum, _freq_sum_            
              
def fft_mean(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.mean(freq_spectrum)
              
def fft_var(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.var(freq_spectrum)
              
def fft_abs_diff(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.mean(np.absolute(freq_spectrum - np.mean(freq_spectrum)))

def fft_min(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.min(freq_spectrum)

def fft_min(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.max(freq_spectrum)

def fft_max_min_diff(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.max(freq_spectrum) - np.min(freq_spectrum)

def fft_median(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.median(freq_spectrum)

def fft_med_abs_dev(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    x_feat = median_absolute_deviation(freq_spectrum)
    return x_feat

def fft_iqr(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    x_feat = np.percentile(freq_spectrum,75)-np.percentile(freq_spectrum,25)
    return x_feat

def fft_cross_mean(x):
    count = 0;
    freq_spectrum, _freq_sum_ = fft_fft(x)
    for i in range(len(freq_spectrum)-1):
        if (freq_spectrum[i] - np.mean(freq_spectrum)) * (freq_spectrum[i+1] - np.mean(freq_spectrum)) < 0:
            count = count + 1 
    return count

def fft_above_mean(x):
    count = 0
    freq_spectrum, _freq_sum_ = fft_fft(x)
    for i in range(len(freq_spectrum)):
        if (freq_spectrum[i] - np.mean(freq_spectrum)) > 0:
            count = count + 1 
    return count

def fft_below_mean(x):
    count = 0
    freq_spectrum, _freq_sum_ = fft_fft(x)
    for i in range(len(freq_spectrum)):
        if (freq_spectrum[i] - np.mean(freq_spectrum)) < 0:
            count = count + 1 
    return count

def fft_number_peaks(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return len(find_peaks(freq_spectrum))

def fft_rms(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.sqrt(np.mean(np.square(freq_spectrum)))

def fft_sr(x): # square root
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.square(np.mean(np.sqrt(np.abs(freq_spectrum))))

def fft_am(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.mean(np.abs(freq_spectrum))

def fft_kurt(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    x_feat = kurtosis(freq_spectrum)
    return x_feat

def fft_kurt_index(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    n = len(freq_spectrum)
    temp1 = np.sum(( freq_spectrum - mean_acc( freq_spectrum ))**4)
    temp2 = (np.sqrt(var_acc( freq_spectrum )))**4
    return temp1 / ((n-1)*temp2)

def fft_skew(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    x_feat = skew(freq_spectrum)
    return x_feat

def fft_skew_index(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    n     = len(freq_spectrum)
    temp1 = np.sum((freq_spectrum - mean_acc(freq_spectrum))**3)
    temp2 = (np.sqrt( var_acc(freq_spectrum) ))**3
    return temp1/((n-1)*temp2)

def fft_shape_mean(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    shape_sum = np.sum([xi * freq_spectrum[xi] for xi in range(len(freq_spectrum))])
    return 0 if _freq_sum_ < epsn else shape_sum * 1.0 / _freq_sum_

def fft_shape_std(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    shape_mean = fft_shape_mean(sequence_data)
    var = np.sum([0 if _freq_sum_ < epsn else np.power((x - shape_mean), 2) * freq_spectrum[x] for x in range(len(freq_spectrum))]) / _freq_sum_
    return np.sqrt(var)

def fft_shape_skew(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    shape_mean = fft_shape_mean(sequence_data)
    return np.sum([np.power((x - shape_mean), 3) * freq_spectrum[x] for x in range(len(freq_spectrum))]) / _freq_sum_

def fft_shape_kurt(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    shape_mean = fft_shape_mean(sequence_data)
    return np.sum([np.power((x - shape_mean), 4) * freq_spectrum[x] - 3 for x in range(len(freq_spectrum))]) / _freq_sum_

def fft_energy(x):
    freq_spectrum, _freq_sum_ = fft_fft(x)
    return np.sum(freq_spectrum ** 2) / len(freq_spectrum)

def fft_entropy(sequence_data):
    freq_spectrum, _freq_sum_ = fft_fft(sequence_data)
    pr_freq = freq_spectrum * 1.0 / _freq_sum_
    entropy = -1 * np.sum([np.log2(p+1e-5) * p for p in pr_freq])
    return entropy

In [3]:
print('Resample to Frequency Rate ... ')
start_time    = time.time()                # To keep track of time to run the code
def re_sample(name):
    data1         = pd.read_csv(name) # Loading Accelerometer data
    acc_x         = data1.acc_x
    time_series   = data1.ts_receiver
    sample_rate   = len(time_series)/(time_series[len(time_series)-1] - time_series[0])
    signal_len    = len(acc_x)
    resample_rate = 256
    resample_len  = int(signal_len / sample_rate * 256)
    return resample_len

def sliding_window_seg(data_s, windowSize, windowstep):  # 200Hz data
    data = np.array(data_s)
    w_range = int((len(data) - windowSize + windowstep)/windowstep)
    window_var = []
    a = 0
    b = a + windowSize - 1
    i = 0
    while i < w_range:
        w_data = data[a:b]
        window_var.append(np.var(w_data))
        a = a + windowstep
        b = b + windowstep
        i = i + 1
    window_var = np.array(window_var)
    threshold = 420  # set larger threshold for a more fined segmentation
    var_b = window_var < threshold
    var_b = var_b * 1

    # check whether there are fake pauses, which has pause time < 3 windows (~300ms)
    pauses = []
    pauses_count = 0
    for i in range(len(var_b)):
        if var_b[i] == 1:
            pauses.append(i)
        else:
            if 0 < len(pauses) <= 3:
                var_b[pauses] = 0
                pauses_count += 1
            pauses = []
    print('Detected and removed {} fake pauses'.format(pauses_count))
    segment = {}  # segment data where number of (var_b == 0) > 500ms
    seg_point = []
    count = 0
    for i in range(len(var_b)):
        # print(var_b[i])
        if var_b[i] == 0:
            seg_point.append(i)
        else:
            if seg_point:
                count += 1
                segment[count] = seg_point
                seg_point = []
    if var_b[-1] == 0:
        count += 1
        segment[count] = seg_point
    start_end = []
    for i in range(len(segment)):
        seg = np.array(segment[i+1])
        if len(seg) > 5:  #around 300ms
            start = seg[0] * windowstep
            end = seg[-1] * windowstep + windowSize - 1
            start_end.append([start, end])
    return start_end, threshold

Resample to Frequency Rate ... 


In [4]:
#提取特征,调用了max,min,mean, 然后cat到一起,axis=none代表三个特征在同一行里,这样每个x的三个特征就在同一行里
def extract_timfeature(data):
    feature_tim = []
    result = []

    mean_acc_data = mean_acc(data)
    #std_acc_data = std_acc(data)

    max_acc_data = max_acc(data)
    min_acc_data = min_acc(data)
    #pk_data = max_acc_data - min_acc_data
        
    #print(max_acc_data)
    
    #feature_tim = max_acc_data
    feature_tim = np.concatenate((max_acc_data, min_acc_data, mean_acc_data), axis=None)
    #feature_tim[2,:] = min_acc_data
    #feature_tim[3,:] = mean_acc_data
    result.append(feature_tim)
        #print(result)
    return np.array(result)
#传入data和sp的数据,利用分片的信息,获得每一片sub_data,然后调用extract_timfeature提取max,min,mean, 并且按照分片的顺序加到results里
#最后output是一个10*3的矩阵,因为我们只想取前10个sample的数据,10个sample三个特征
def get_feature(data, sp):
    results = []
    for i in range(len(sp)):
        sub_data = data[sp[i]]
        result = extract_timfeature(sub_data)
        results.append(result)
    return np.array(results).reshape(10,3)

In [5]:
# def getFeature(name_left, name_right):
    
#     # name_left = "C:/Users/analy/Documents/test/data_set/subject2/word/s2_ARROGANT_leftear_s1.csv"
#     data_left = pd.read_csv(name_left)
#     data_left = data_left.drop(['ts_receiver','ts_sensor','mag_x','mag_y','mag_z'], axis=1)
#     resample_len = data_left.shape[0]
#     #print(data_left.shape)
#     data_left = signal.resample(data_left, resample_len, axis = 0)
#     feature_left = extract_timfeature(data_left)

#     # name_right = "C:/Users/analy/Documents/test/data_set/subject2/word/s2_ARROGANT_rightear_s1.csv"
#     data_right = pd.read_csv(name_right)
#     data_right = data_right.drop(['ts_receiver','ts_sensor','mag_x','mag_y','mag_z'], axis=1)
#     data_right = signal.resample(data_right, resample_len, axis = 0)
#     feature_right = extract_timfeature(data_right)

#     feature = np.concatenate((feature_left, feature_right), axis=None)
    
#     return feature

In [5]:
#设置工作空间,输出feature文件的地方(下一个cell)
path = "D:/test/3project/3feature_713"
os.chdir(path)
os.getcwd()

'D:\\test\\3project\\3feature_713'

In [74]:
#手动更改第5行,第88行,第96行, 如果是subject2,就都改成2,如果是subject4,都改成4,重复6次,因为是实验,这样手动改方便看每次提取出来的特征长啥样,分的好不好.如果一次跑完了打出来东西太多不容易检查
#调参是调37行的分片数据
import os
#设置读取文件的路径,这里我把需要扫的6个文件放到sub里,因为我们并不需要使用全部的word文件(很多文件只有9个sample,还有typo,还有有的subject单词不全,所以我把挑出来能用的放到了sub文件夹里)
filePath = "D:/test/data_set/subject2/word/sub"
names    = os.listdir(filePath);

#用一个字典final_feature 存每个word(key)的feature(value) pairs
final_feature = {}
#用来看最后6个单词每个pause分片的情况的,毕竟尽量分成10个或者11个最好
total_pause = []
check = ['hand']
for nn in range(len(names)):

    curr_file = filePath + '/' + names[nn];
    (filePathin1, tempfilename1) = os.path.split(curr_file)
    # print('curren_file_is', curr_file)
    # print('the current temp file name is', tempfilename1)

    session = tempfilename1.split('_')[-2]
    # print('the session is', session)
    if session in check:
        name      = curr_file
        left      = tempfilename1.split('_')[:-2]
        left_right = ''
        for left_i in range(len(left)):
            left_right = left_right + left[left_i] + '_' 
         #读文件名   
        name_hand  = curr_file
        name_left  = filePath + '/' + left_right + 'leftear_s1.csv'
        name_right = filePath + '/' + left_right + 'rightear_s1.csv'
        print('the name of hand should be',name_hand)
        resample_len  = re_sample(name_hand)
        print('the resample length should be', resample_len)
        data1 = pd.read_csv(name_hand)		#Loading Accelerometer data
        acc_x1 = data1.acc_x
        acc_x1 = signal.resample(acc_x1, resample_len)
        sp,th = sliding_window_seg(acc_x1, 340, 40)
        total_pause.append(len(sp))
        
        #打印一共分了多少个sample
        print("pause:",len(sp))
        
        #获取前10个sample分片的上界和下界
        sp = sp[0:10]
        print("pause for each sample: ", sp)
        
        #left
        data2         = pd.read_csv(name_left)
        acc_x2        = data2.acc_x
        #print ("before resample acc_x2", acc_x2.shape)
        acc_y2        = data2.acc_y
        acc_z2        = data2.acc_z
        acc_x2        = signal.resample(acc_x2, resample_len, axis = 0)
        #print ("acc_x2", acc_x2.shape)
        acc_y2        = signal.resample(acc_y2, resample_len, axis = 0)
        acc_z2        = signal.resample(acc_z2, resample_len, axis = 0)
        print("data_shape: ", data2.shape)
        feature_left_acc_x2 = get_feature(acc_x2,sp)
        feature_left_acc_y2 = get_feature(acc_y2,sp)
        feature_left_acc_z2 = get_feature(acc_z2,sp)
        print("feature_left_acc_x:", feature_left_acc_x2)
        print("feature_left_acc_y:", feature_left_acc_y2)
        print("feature_left_acc_z:", feature_left_acc_z2)
        
        print("\n")
        
        #right
        data3         = pd.read_csv(name_right)
        acc_x3        = data3.acc_x
        acc_y3        = data3.acc_y
        acc_z3        = data3.acc_z
        acc_x3         = signal.resample(acc_x3, resample_len, axis = 0)
        acc_y3         = signal.resample(acc_y3, resample_len, axis = 0)
        acc_z3         = signal.resample(acc_z3, resample_len, axis = 0)
        feature_right_acc_x3 = get_feature(acc_x3,sp)
        feature_right_acc_y3 = get_feature(acc_y3,sp)
        feature_right_acc_z3 = get_feature(acc_z3,sp)
        print("feature_right_acc_x:", feature_right_acc_x3)
        print("feature_right_acc_y:", feature_right_acc_y3)
        print("feature_right_acc_z:", feature_right_acc_z3)
        
        print("\n")
        
        name_left  = filePath + '/' + left_right + 'leftear_s1.csv'
        name_right = filePath + '/' + left_right + 'rightear_s1.csv'
        # print("left_right", left_right)
        word = left_right.strip('s2').strip('_')
        #就是把每个单词的左右xyz 按行cat到一起
        feature = np.concatenate((feature_left_acc_x2, feature_left_acc_y2, feature_left_acc_z2, feature_right_acc_x3, feature_right_acc_y3, feature_right_acc_z3), axis=1)
        print("feature:", feature)
        final_feature[word] = feature
        # print(feature)
        print("\n\n\n")
print("total_pause for each word: ", total_pause)
np.save('s2_left_right.npy', final_feature)

the name of hand should be D:/test/data_set/subject2/word/sub/s2_CHAPLATE_hand_s1.csv
the resample length should be 18467
Detected and removed 4 fake pauses
pause: 10
pause for each sample:  [[160, 1499], [1840, 3379], [4120, 5539], [5680, 7139], [7360, 8779], [9320, 10619], [10800, 12379], [12400, 13779], [14320, 15739], [16200, 17779]]
data_shape:  (8805, 11)
feature_left_acc_x: [[-626.87106646 -627.9262614  -627.39866393]
 [-600.62688261 -617.65704769 -609.14196515]
 [-604.24339833 -608.00144696 -606.12242264]
 [-605.99478141 -611.11777057 -608.55627599]
 [-611.17294337 -613.62900898 -612.40097618]
 [-605.68833609 -612.03036814 -608.85935212]
 [-604.20796003 -616.95435684 -610.58115844]
 [-595.7662752  -610.56386517 -603.16507019]
 [-587.41811814 -606.19327659 -596.80569737]
 [-594.05228993 -613.83122603 -603.94175798]]
feature_left_acc_y: [[765.26695015 760.00106515 762.63400765]
 [783.78662703 773.15735251 778.47198977]
 [783.3128923  775.02498265 779.16893748]
 [782.14611816 777.

In [73]:
#方便看total_pause for each word, 调整分片参数,筛数据用的